# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_content',
            new_name='approved_comment',
        ),
    ]
